name: master

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: aztfmod 
        # Container registry password
        password: ${{ secrets.docker_registry_password }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
    - name: Build the rover
      run: |
        set -e
        docker_tag=$(date +"%g%m.%d%H")
        echo ::set-env name=docker_tag::${docker_tag}

        # Build the rover base image
        docker-compose build --build-arg versionRover="aztfmod/rover:$docker_tag"

        docker tag rover_rover aztfmod/rover:$docker_tag
        docker push aztfmod/rover:$docker_tag

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.docker_tag }}
        release_name: aztfmod/rover:${{ env.docker_tag }}
        draft: false
        prerelease: true